name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the issue.
      placeholder: Describe what is wrong.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - UI (React)
        - API Implementation
        - Types/library
        - Other
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
